- name: generate | initialize corosync authkey
  block:
    - name: generate | install haveged
      apt:
        name: haveged
        state: present

    - name: generate | reset auth
      file:
        path: /etc/corosync/authkey
        state: absent

    - name: generate | generate a new authkey
      command: /usr/sbin/corosync-keygen

    - name: generate | wait for key
      wait_for:
        path: /etc/corosync/authkey
        timeout: 30
      notify: restart corosync

    - name: generate | slurp /etc/corosync/authkey
      slurp:
        src: /etc/corosync/authkey
      register: authkey_slurp

    - name: generate | save /etc/corosync/authkey into dummy host
      add_host:
        name: _authkey_dummy
        authkey_content:  "{{ authkey_slurp['content'] | b64decode }}"
      no_log: yes
      changed_when: no

    - name: generate | unininstall haveged
      apt:
        name: haveged
        state: absent
        purge: true
