---

- name: hosts | exchange hostnames in hosts file
  blockinfile:
    path: /etc/hosts
    block: |
            {% if item != '_authkey_dummy' %}{% if corosync_use_internal_ip|bool %} {{ hostvars[item]['internal_ip'] }} {{ hostvars[item]['ansible_hostname'] }}{% else %}{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['ansible_hostname'] }}{% endif %}{% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  loop: "{{ query('inventory_hostnames', 'all') }}"
