---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: focal1
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

  - name: focal2
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        corosync_hacluster_password: 1q2w3e4r5t

verifier:
  name: ansible
